# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: handwriting.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'handwriting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11handwriting.proto\x12\x0bhandwriting\"<\n\x12HandwritingRequest\x12&\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x16.handwriting.DrawEvent\"z\n\tDrawEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08\x62oard_id\x18\x03 \x01(\t\x12)\n\x07payload\x18\x04 \x01(\x0b\x32\x18.handwriting.DrawPayload\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"S\n\x0b\x44rawPayload\x12\"\n\x06points\x18\x01 \x03(\x0b\x32\x12.handwriting.Point\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x11\n\tthickness\x18\x03 \x01(\x05\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"=\n\x13HandwritingResponse\x12&\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x16.handwriting.DrawEvent2i\n\x15HandwritingRecognizer\x12P\n\tRecognize\x12\x1f.handwriting.HandwritingRequest\x1a .handwriting.HandwritingResponse\"\x00\x42\x1dZ\x1b./handwriting;handwritingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'handwriting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033./handwriting;handwritingpb'
  _globals['_HANDWRITINGREQUEST']._serialized_start=34
  _globals['_HANDWRITINGREQUEST']._serialized_end=94
  _globals['_DRAWEVENT']._serialized_start=96
  _globals['_DRAWEVENT']._serialized_end=218
  _globals['_DRAWPAYLOAD']._serialized_start=220
  _globals['_DRAWPAYLOAD']._serialized_end=303
  _globals['_POINT']._serialized_start=305
  _globals['_POINT']._serialized_end=334
  _globals['_HANDWRITINGRESPONSE']._serialized_start=336
  _globals['_HANDWRITINGRESPONSE']._serialized_end=397
  _globals['_HANDWRITINGRECOGNIZER']._serialized_start=399
  _globals['_HANDWRITINGRECOGNIZER']._serialized_end=504
# @@protoc_insertion_point(module_scope)
