// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: handwriting.proto

package handwritingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandwritingRecognizer_Recognize_FullMethodName = "/handwriting.HandwritingRecognizer/Recognize"
)

// HandwritingRecognizerClient is the client API for HandwritingRecognizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandwritingRecognizerClient interface {
	Recognize(ctx context.Context, in *HandwritingRequest, opts ...grpc.CallOption) (*HandwritingResponse, error)
}

type handwritingRecognizerClient struct {
	cc grpc.ClientConnInterface
}

func NewHandwritingRecognizerClient(cc grpc.ClientConnInterface) HandwritingRecognizerClient {
	return &handwritingRecognizerClient{cc}
}

func (c *handwritingRecognizerClient) Recognize(ctx context.Context, in *HandwritingRequest, opts ...grpc.CallOption) (*HandwritingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandwritingResponse)
	err := c.cc.Invoke(ctx, HandwritingRecognizer_Recognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandwritingRecognizerServer is the server API for HandwritingRecognizer service.
// All implementations must embed UnimplementedHandwritingRecognizerServer
// for forward compatibility.
type HandwritingRecognizerServer interface {
	Recognize(context.Context, *HandwritingRequest) (*HandwritingResponse, error)
	mustEmbedUnimplementedHandwritingRecognizerServer()
}

// UnimplementedHandwritingRecognizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandwritingRecognizerServer struct{}

func (UnimplementedHandwritingRecognizerServer) Recognize(context.Context, *HandwritingRequest) (*HandwritingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedHandwritingRecognizerServer) mustEmbedUnimplementedHandwritingRecognizerServer() {}
func (UnimplementedHandwritingRecognizerServer) testEmbeddedByValue()                               {}

// UnsafeHandwritingRecognizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandwritingRecognizerServer will
// result in compilation errors.
type UnsafeHandwritingRecognizerServer interface {
	mustEmbedUnimplementedHandwritingRecognizerServer()
}

func RegisterHandwritingRecognizerServer(s grpc.ServiceRegistrar, srv HandwritingRecognizerServer) {
	// If the following call pancis, it indicates UnimplementedHandwritingRecognizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandwritingRecognizer_ServiceDesc, srv)
}

func _HandwritingRecognizer_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandwritingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandwritingRecognizerServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandwritingRecognizer_Recognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandwritingRecognizerServer).Recognize(ctx, req.(*HandwritingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandwritingRecognizer_ServiceDesc is the grpc.ServiceDesc for HandwritingRecognizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandwritingRecognizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handwriting.HandwritingRecognizer",
	HandlerType: (*HandwritingRecognizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _HandwritingRecognizer_Recognize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handwriting.proto",
}
